title: Mehrdad Mokhtari # your name (or website title) here
logo: "/images/PFP.HEIC?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Co-instructur and developer of<a href="https://www.sfu.ca/big-data/online-data-science-course-data-fellowships?utm_source=Email_marketing&utm_medium=HTMLEmail&utm_campaign=Data_Fellowships">"SFU DATA FELLOWSHIPS: AI ESSENTIALS" Workshop</a> 
  <br><br>
  <b>Machine Learning Consultant at Big Data Hub, SFU</b>
  <br><br>
  <a href="https://www.linkedin.com/in/mehrdad93/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-175440147-1 # your Google Analytics tracking ID here
