title: Mehrdad Mokhtari # your name (or website title) here
logo: "/images/IMG_7723.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.sfu.ca/big-data/online-data-science-course-data-fellowships?utm_source=Email_marketing&utm_medium=HTMLEmail&utm_campaign=Data_Fellowships">Co-instructur and developer of the "SFU DATA FELLOWSHIPS: AI ESSENTIALS" Workshop</a> 
  <br><br>
  Machine Learning Consultant at Big Data Hub, SFU
  <br><br>
  <a href="https://www.linkedin.com/in/mehrdad93/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-175440147-1 # your Google Analytics tracking ID here
