title: Mehrdad Mokhtari # your name (or website title) here
logo: "/images/PFP.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Co-instructur and co-developer of <a href="https://www.sfu.ca/big-data/online-data-science-course-data-fellowships?utm_source=Email_marketing&utm_medium=HTMLEmail&utm_campaign=Data_Fellowships">"SFU DATA FELLOWSHIPS: AI ESSENTIALS"</a> 
  <br><br>
  Machine Learning Consultant at <a href="https://www.sfu.ca/big-data/about">Big Data Hub, SFU</a>
  <br><br>
  <a href="https://www.linkedin.com/in/mehrdad93/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/Mehrdad93/CV/blob/master/Mehrdad_Mokhtari_CV.pdf">View My Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-175440147-1 # your Google Analytics tracking ID here
