title: Mehrdad Mokhtari # your name (or website title) here
logo: "/images/IMG_7723.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ML
  <br><br>
  Machine Learning Consultant at Big Data Hub, SFU
  <br><br>
  <a href="https://www.linkedin.com/in/mehrdad93/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-175440147-1 # your Google Analytics tracking ID here
